name: UnlimitedFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 4.3
description: Plugin for the Unlimited Freedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Madgeek1450, Prozza, TaahThePhoenix, Verdon_Online]

# plugin.yml is no longer used to define commands.
